name: provider_architectire
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  simple_html_css: ^5.0.0

  # 상태관리 라이브러리
  flutter_hooks: ^0.20.5

  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 네트워크 통신 라이브러리
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.3

  # 데이터 직렬화를 위한 라이브러리
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  collection: ^1.18.0
  uuid: ^4.5.1

  # 이미지 캐싱 라이브러리
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3

  # 디버깅 로그 라이브러리
  logger: ^2.4.0

  # 로컬 스토리지 라이브러리
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_dotenv: ^5.2.1
  go_router: ^14.3.0
  mockito: ^5.4.4

  responsive_builder:
    ^0.7.1

    # 로컬 스토리지
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.1.0
  web: ^1.1.0
  file_picker: ^8.1.3
  flutter_dropzone: ^4.0.3
  excel: ^4.0.6
  fluttertoast: ^8.2.8
  two_dimensional_scrollables: ^0.3.3
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.8

  # 상태관리 코드 생성 라이브러리
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  riverpod_lint: ^2.6.1

  # 데이터 직렬화 코드 생성 라이브러리
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
